[project]
name = "face-lock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "facenet-pytorch>=2.5.3",
    "jupyter>=1.1.1",
    "opencv-python>=4.12.0.88",
]
